language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g codecov nyc
script:
  - nyc mocha tests/*.spec.js --require babel-core/register
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
